# Generated by Django 5.1.4 on 2025-01-03 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=32)),
            ],
            options={
                "db_table": "beer",
            },
        ),
        migrations.CreateModel(
            name="BeerDescription",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                (
                    "beer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descriptions",
                        to="beer.beer",
                    ),
                ),
            ],
            options={
                "db_table": "beer_description",
            },
        ),
        migrations.CreateModel(
            name="BeerImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.CharField(max_length=100, null=True)),
                (
                    "beer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="beer.beer",
                    ),
                ),
            ],
            options={
                "db_table": "beer_image",
            },
        ),
        migrations.CreateModel(
            name="BeerPrice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.IntegerField()),
                (
                    "beer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="beer.beer",
                    ),
                ),
            ],
            options={
                "db_table": "beer_price",
            },
        ),
    ]
