# Generated by Django 5.1.3 on 2025-01-02 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whiskey", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhiskeyPrice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.IntegerField()),
                (
                    "whiskey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="whiskey.whiskey",
                    ),
                ),
            ],
            options={
                "db_table": "whiskey_price",
            },
        ),
    ]
