# Generated by Django 5.1.3 on 2025-01-09 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alcohol", "0001_initial"),
        ("whiskey", "0002_whiskeyprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="whiskey",
            name="alcohol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="whiskey_alcohols",
                to="alcohol.alcohol",
            ),
        ),
    ]
