# Generated by Django 5.1.3 on 2025-01-10 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0002_wine_alcohol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wine",
            name="title",
        ),
    ]
