# Generated by Django 5.1.4 on 2025-01-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=32)),
            ],
            options={
                "db_table": "account",
            },
        ),
    ]
