# Generated by Django 5.1.4 on 2025-01-10 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountRoleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("NORMAL", "Normal"),
                            ("SUBSCRIBE", "Subscribe"),
                        ],
                        default="NORMAL",
                        max_length=64,
                    ),
                ),
            ],
            options={
                "db_table": "account_role_type",
            },
        ),
        migrations.AddField(
            model_name="account",
            name="role_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.accountroletype",
            ),
        ),
    ]
