# Generated by Django 5.1.4 on 2025-01-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alcohol",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=32)),
                ("price", models.IntegerField()),
                ("image", models.CharField(max_length=100, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BEER", "BEER"),
                            ("WHISKEY", "WHISKEY"),
                            ("WINE", "WINE"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
            options={
                "db_table": "alcohol",
            },
        ),
    ]
