# Generated by Django 5.1.3 on 2025-01-06 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlcoholImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.CharField(max_length=100, null=True)),
            ],
            options={
                "db_table": "alcohol_image",
            },
        ),
        migrations.CreateModel(
            name="Alcohol",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=32)),
                ("price", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BEER", "BEER"),
                            ("WHISKEY", "WHISKEY"),
                            ("WINE", "WINE"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="alcohol.alcoholimage",
                    ),
                ),
            ],
            options={
                "db_table": "alcohol",
            },
        ),
    ]
