# Generated by Django 5.1.3 on 2024-12-31 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alcohol",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=32)),
            ],
            options={
                "db_table": "alcohol",
            },
        ),
        migrations.CreateModel(
            name="AlcoholCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "alcoholCategory",
                    models.CharField(
                        choices=[
                            ("BEER", "Beer"),
                            ("WINE", "Wine"),
                            ("WHISKEY", "Whiskey"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "alcohol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="alcohol_store.alcohol",
                    ),
                ),
            ],
            options={
                "db_table": "alcohol_category",
            },
        ),
        migrations.CreateModel(
            name="AlcoholDescription",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                (
                    "alcohol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descriptions",
                        to="alcohol_store.alcohol",
                    ),
                ),
            ],
            options={
                "db_table": "alcohol_description",
            },
        ),
        migrations.CreateModel(
            name="AlcoholImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.CharField(max_length=100, null=True)),
                (
                    "alcohol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="alcohol_store.alcohol",
                    ),
                ),
            ],
            options={
                "db_table": "alcohol_image",
            },
        ),
        migrations.CreateModel(
            name="AlcoholPrice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.IntegerField()),
                (
                    "alcohol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="alcohol_store.alcohol",
                    ),
                ),
            ],
            options={
                "db_table": "alcohol_price",
            },
        ),
    ]
